function action = generateAction(p)
%GENERATEACTION  The Patient generator's Generate action for a parameter struct.
%   Draws every patient attribute from the programme's measured rates:
%   referable (true DR state), aiPositive (sensitivity / specificity),
%   flagged (review flag rate), toDoctor, route (1 -> doctor, 2 -> discharge:
%   the Entity Output Switch reads the attribute as the port index),
%   readerCalls (human reader), service times, outcome (1 -> discharge,
%   2 -> missed referable). Used by buildDistrictModel and, per run, by
%   runSweep's Simulink path so a sweep changes only this string and `params`.
    nl = newline;
    action = [ ...
        sprintf('entity.referable = double(rand < %g);', p.referablePrevalence) nl ...
        sprintf('if entity.referable, entity.aiPositive = double(rand < %g); else, entity.aiPositive = double(rand < %g); end', p.sensitivity, 1 - p.specificity) nl ...
        sprintf('entity.flagged = double(rand < %g);', p.flagRate) nl ...
        sprintf('entity.toDoctor = double(%d && (entity.aiPositive || entity.flagged)) + double(~%d);', p.aiEnabled, p.aiEnabled) nl ...
        'entity.route = 2 - entity.toDoctor;' nl ...
        sprintf('if entity.referable, entity.readerCalls = double(rand < %g); else, entity.readerCalls = double(rand < %g); end', p.humanReaderSensitivity, 1 - p.humanReaderSpecificity) nl ...
        sprintf('entity.captureMinutes = %g * (1 + double(rand < %g));', p.captureMinutes, p.retakeProbability) nl ...
        sprintf('entity.reviewMinutes = %g + %g * entity.readerCalls;', p.teleReviewMinutes, p.inPersonMinutes) nl ...
        'entity.outcome = 1 + entity.referable;' nl];
end
